name: app1
Ecosystem: app1
Agent: mydockeragent
Build:
  Techno: mvn
    BuildOptions: '-s settings.xml'
  Techno: dotnet
    SlnFileName: myproject.sln
  ArtifactoryDeploy: True
  Techno: sql
    localPath: apps/sql
Sonar:
  SonarID: app1
  SonarCredentials: sonar-api-key
  SonarOptions: [JAVA_HOME=/app/jdk1.8, CPU=3]
SecurityScan:
  SAST: True
  SASTConfig:
    RefVersion: 1.0.0
    TargetVersion: refer from pom.xml for maven or nuget.spec file for dotnet
    CustomTargetVersion: 2.0.0
  SCA: True
Deploy:
  skip: true
  agent: myansibleagent
  environmentList: [dev,uat,prod]
  defaultEnv: dev
  AnsibleDeploymentThroughAPI: false
  AnsibleRepo: deployment
  AnsibleRepoBranch: main
